### ISSUE TITLE
Error on first start, it just doesnt install

### ISSUE THREAD

**Issue by ixon8** [IzzelAliz/Arclight#1331]
### I have confirmed that ...

- [X] Arclight is up to date
- [X] all dependencies are installed
- [X] all plugins and mods are up to date
- [X] unable to reproduce in Spigot
- [X] unable to reproduce in Forge

### Arclight version

arclight-1.18.2-1.0.x

### OS & Java versions

OS: Windows 10 Java: 22.0.1

### Plugins and Mods

```raw
none
```

### Description

I execute the arclight file (any version, i have tried every version for 1.18.2) and it throws an error, no folders are made or files dropped to the folder

### Step to reproduce

1: try to install 1.18.2 arclight server
2: it just throws error
![image](https://github.com/IzzelAliz/Arclight/assets/39270116/eae94663-d2f0-4de8-aa55-d5e459891fd2)

**Comment by GAMINGCHATS** [comment]
First of all open a command prompt window and run `java -version`.
If it shows something like this: 
![image](https://github.com/IzzelAliz/Arclight/assets/90594728/626652fa-8704-4585-a6e2-439e17d38572)
then the java version you have installed is (in the scenario in the picture) `java version "21.0.2" 2024-01-16 LTS`
If it shows you `'java' is not recognized as an internal or external command,
operable program or batch file.` it means you don't have java installed. 
Since you're running 1.18.2 and it doesn't start it's likely you have an older version of java rather than the required one which is Java 17 and/or newer. 
In the command `java -jar arclight.jar` replace `java` with the path java 17 (newer is installed). 
Here is an example demonstrated with java 8:
`
"C:\Program Files\Java\jre-1.8\bin\java.exe" -jar arclight.jar nogui
pause
`
The `nogui` disables the server control panel andthe `pause` argument makes it when the server stops for the app to close you have to press any key. (That's my addition btw)
Don't forget the path needs to end with `\bin\java.exe`

**P.S.** I'm no tech genius but I'm interested in tech generally and the above solution was found by some server in Discord which I don't remember. I hope that fixes your problem.

**Comment by GAMINGCHATS** [comment]
**UPDATE**:
Found this in `https://wiki.izzel.io/s/arclight-docs/doc/faqs-ApcZ25PXVT`:
`
Java version?
For 1.18 / 1.19:

HotSpot 17 ~ 18

IBM Semeru(OpenJ9) - Not supported due to Forge restriction

For 1.16:

HotSpot 1.8 ~ 17

IBM Semeru(OpenJ9) 17
`

**Comment by IzzelAliz** [comment]
Switch to an older Java version like 17. 1.18 do not support Java 22 yet.
