### ISSUE TITLE
New forge update 1.19.2 issues

### ISSUE THREAD

**Issue by Tr3yWay996** [IzzelAliz/Arclight#1532]
### I have confirmed that ...

- [X] Arclight is up to date
- [X] all dependencies are installed
- [X] all plugins and mods are up to date
- [X] unable to reproduce in Spigot
- [X] unable to reproduce in Forge

### Arclight version

arclight-forge-1.19.2-1.0.6-SNAPSHOT

### OS & Java versions

Ubuntu 22.4 LTS Java 17 (ghcr.io/pterodactyl/yolks:java_17)

### Plugins and Mods

```raw
EssentialsX
```

### Description

EssentialsX get automatically disabled and nothing related to it work

### Step to reproduce

Use this build of 1.19.2 of arclight and try installing EssentialsX
[Arclight.zip](https://github.com/user-attachments/files/17441072/Arclight.zip)

### Logs

[latest(1).log](https://github.com/user-attachments/files/17441079/latest.1.log)

**Comment by Tr3yWay996** [comment]
I just got this when starting the server too, and yes i'm trying different versions
[log22.txt](https://github.com/user-attachments/files/17444527/log22.txt)

**Comment by qyl27** [comment]
I think this problem is caused by the way `EssentialsX` was implemented to find the NMS.  
They have predefined the NMS package name pattern in https://github.com/EssentialsX/Essentials/blob/c80bef984181af78690353b22fd0a9892291d5e3/providers/NMSReflectionProvider/src/main/java/net/ess3/nms/refl/ReflUtil.java#L254-L265 .  
This problem will be reproduced in other Arclight versions.  
There are many plugins like `EssentialsX` you could use, such as `CMI`.

**Comment by qyl27** [comment]
Sorry, that is my mistake, fixed

**Comment by Tr3yWay996** [comment]
> Sorry, that is my mistake, fixed

I'm late but how do i actually build it ? I keep getting "build failed" when i try
