### ISSUE TITLE
Two issues

### ISSUE THREAD

**Issue by Sunconure11** [IzzelAliz/Arclight#209]
1. This appears to be incompatible with Crucial 2. Attempting to boot it with such results in this: https://pastebin.com/T0TaQZLF
2. When attempting to use this on a Valhelsia 2 server, when one attempts to enter, they remain stuck at “encrypting”, while the log states they timed out

Of note is that I am using a plan purchased from Pebblehost for the servers. I had discussed this with them and they told me to come here.

**Comment by Sunconure11** [comment]
Packs in question can be found below:

https://www.curseforge.com/minecraft/modpacks/crucial-2

https://www.curseforge.com/minecraft/modpacks/valhelsia-2

**Comment by Sunconure11** [comment]
![F5D4C3DE-F466-4741-B7DA-F780B8F5F255](https://user-images.githubusercontent.com/5614902/112596866-c4dee780-8de2-11eb-986d-8a6fdd6869b3.png)

**Comment by segg21** [comment]
I don't know about **Crucial**, but **Valhelsia** won't work due to the fact is has [**RandomPatches**](https://www.curseforge.com/minecraft/mc-mods/randompatches-forge).

I'm using a custom private mod pack, and this mod initially I had but as you stated "stuck at encrypting/time out" this mod prevented players from joining the server.

**Comment by segg21** [comment]
Also it seems like you're not running on a dedicated host, so Archlight is unable to install forge? Try running Archlight (once locally), and move the .jars, and libraries folder to your host. That should work, instead of Archlight trying to download forge.

**Comment by Sunconure11** [comment]
I’m able to install forge. The issue is that Arclight is trying to use its own version of Java, which the host does not support.

**Comment by Sunconure11** [comment]
@LegitSoulja RandomPatches also has a fix of it's own for the timing out stuff. Is there some way I can get around that, without reinstalling said mod?

**Comment by segg21** [comment]
> I’m able to install forge. The issue is that Arclight is trying to use its own version of Java, which the host does not support.

ArchLight doesn't use it's own Java, it uses Java (A separate process to install Forge). Something within this process your host limits access (Obviously executing other scripts within 1 instance). Atleast, that is what it seems like. 

I'm running on a dedicated server so never came across this issue, but can see it being an issue on shared hosting. 

> RandomPatches also has a fix of it's own for the timing out stuff. Is there some way I can get around that, without reinstalling said mod?

I don't entirely know what patches RandomPatches has, but I would say it's unnecessary. My server has been fine without, 0 timeout issues. 

I've made that comment in regards to RandomPatches so that it could be looked into, as that may be the main issue with that mod pack. I've tested a variety of other mods with ArchLight and haven't found no apparent issues, but capabilities issues may come mixing multiple mods together.

**Comment by Sunconure11** [comment]
I managed to get a bit more into getting the Crucial 2 server working, and I ran into this.

https://pastebin.com/WQ0bxH4w

**Comment by Sunconure11** [comment]
Error still occurs with the dev build.

https://pastebin.com/EevJjukF

**Comment by Sunconure11** [comment]
https://github.com/Mohist-Community/Mohist/issues/1104#event-4528501480
