### ISSUE TITLE
ItemPhysic incompatibility

### ISSUE THREAD

**Issue by HerrBeef** [IzzelAliz/Arclight#50]
### I am running

* **Arclight** [VERSION] arclight-forge-1.15-1.0.9 Snapshot (Commit Fix respawn is not available when FirstAid present)

* **This is the latest development version** Y

* **Java** 8 Update 261

* **Operating System** Windows 10 Pro - 2004

* **Plugins** None

* **Mods**
[CreativeCore v2.0.5](https://www.curseforge.com/minecraft/mc-mods/creativecore) (server runs with creativecore alone)
[ItemPhysic v1.4.5](https://www.curseforge.com/minecraft/mc-mods/itemphysic)

### Description
Crash on Start with ItemPhysic mod

### Step to reproduce
1. Install those mods
2. Run server
3. Error

**Reproducible in Forge** N

### Logs

[ERROR LOG]
<details><pre>
[latest.log](https://github.com/IzzelAliz/Arclight/files/5213824/latest.log)
</pre></details>

**Comment by IzzelAliz** [comment]
After further digging into ItemPhysic, it turns out that this mod complete take over logics inside ItemEntity, which make it nearly impossible to do compatibility in my end.
Ignoring patches to ItemEntity is also not acceptable because several important events are called here.
IMO it is better to contact their developers, like rewriting coremod part of ItemPhysic and not overwriting all methods.

**Comment by ZekerZhayard** [comment]
https://github.com/CreativeMD/ItemPhysic/issues/141

**Comment by ZekerZhayard** [comment]
https://github.com/CreativeMD/ItemPhysic/issues/141#issuecomment-791473424
