### ISSUE TITLE
更新 Forge 版本到 1.18.2 - 40.0.32

### ISSUE THREAD

**Issue by BingYanchi** [IzzelAliz/Arclight#534]
### 请确认您已完成以下几件事

- [X] 正在使用最新的 Arclight
- [X] 已为所有插件及模组安装依赖
- [X] 已为所有插件及模组更新至最新版
- [X] 不可在 Spigot 复现
- [X] 不可在 Forge 复现

### Arclight 版本

arclight-1.18.2-1.0.2-SNAPSHOT-7e71fd13

### Java 版本 | 操作系统

java version "17.0.1" 2021-10-19 LTS

### 相关 Mod/插件 的名称及版本

```raw
Tough+As+Nails-1.18.2-7.0.0.69
```

### 错误描述

略

**Comment by HotoRas** [comment]
Sorry for typing in English because I'm not good at chinese.

Before installing Arclight, place the `Forge Jar` you want to install with at the root of the server, with named as what Arclight server installation downloads.
Or, install Arclight and delete every folder created, and then replace the `Forge Jar` with what you desire, with same filename.
(In this case, you don't have to remove the world folder, `plugins`, `mods` and `config`/`defaultconfig`. Other than that, it's recommended to remove.)
After that, launch Arclight- Arclight will then install the Forge server with version which you want to install.

**Comment by timi137137** [comment]
请详细阅读[FAQ](https://github.com/IzzelAliz/Arclight/wiki/FAQ)
或者查看类似问题 #492
