### ISSUE TITLE
1.18.2 Create Mod chests on contraptions do no contain items collected when they become solid again.

### ISSUE THREAD

**Issue by EricApostal** [IzzelAliz/Arclight#658]
### I have confirmed that ...

- [X] Arclight is up to date
- [X] all dependencies are installed
- [X] all plugins and mods are up to date
- [X] unable to reproduce in Spigot
- [X] unable to reproduce in Forge

### Arclight version

 Version arclight-1.18.2-1.0.6-SNAPSHOT-95085438

### OS & Java versions

OS: Fedora 36 x64, openjdk version "17.0.3" 2022-04-19

### Plugins and Mods

```raw
Mods:
flywheel-forge-1.18-0.6.2.jar : flywheel (1.18-0.6.2) - 1
mods_folder create-mc1.18.2_v0.5.0c.jar : create (0.5.0c) - 1

Plugins:
None
```

### Description

No items appear in the chests of Create contraptions when they become a solid block. They only exist when the contraption is an entity again, so you must use a Portable Storage Interface to retrieve them as chests are un-interactable when a contraption is made into an entity.

[This is a contraption on Forge server](https://i.imgur.com/hZaSDun.mp4).
This is expected behavior. The wood broken appears in the chest, and can be taken out by the player.

[This is the same contraption on Arclight](https://i.imgur.com/P4G8nfP.mp4). 
I can't take any items out when the contraption is solid. However, when it is a moveable object again, I can take them out using a Portable Storage Interface.

### Step to reproduce

1. Run the latest build / dev build of Arclight 1.18.2 and the latest version of Create and Flywheel
2. Make a Create mod contraption that breaks items deposited in a chest on the contraption
3. Use a cart assembler to make the contraption a moveable entity
4. Turn it back into a solid object, and observe the items in the chest. Nothing will be in there, which is in contrast to expected behavior.

### Logs

[latest.log](https://github.com/IzzelAliz/Arclight/files/9155057/latest.log)

**Comment by yanang007** [comment]
Related to #630, #592.
As I was working on an extension of Create's mounted storage system, MoreMountedStorage, I'm quite familiar with this.
It turns out that Create is checking whether the tileentity is **_onlyOpCanSetNbt_** and if it is, Create will refuse to transfer items from mounted storage to real chest block entity. (see [Create/.../NBTProcessors.java](https://github.com/Creators-of-Create/Create/blob/c421f98c18581290f70fc03a7e2a066841a96586/src/main/java/com/simibubi/create/foundation/utility/NBTProcessors.java#L67-L83))
```
	@Nullable
	public static CompoundTag process(BlockEntity tileEntity, CompoundTag compound, boolean survival) {
		// ...
		if (tileEntity.onlyOpCanSetNbt())
			return null;
		return compound;
	}
```
which is overridden by Arclight here:
https://github.com/IzzelAliz/Arclight/blob/c78fe148d33f683183e03fea5c353355f0b9b11b/arclight-common/src/main/java/io/izzel/arclight/common/mixin/core/world/level/block/entity/ChestBlockEntityMixin.java#L61-L64
This, precisely speaking, inherits from Bukkit([a2d26409f70](https://hub.spigotmc.org/stash/projects/SPIGOT/repos/craftbukkit/browse/nms-patches/net/minecraft/world/level/block/entity/TileEntityChest.patch?until=a2d26409f702f712525260ab6eddcfc49cf58d50&untilPath=nms-patches%2FTileEntityChest.patch)), which is used to "SPIGOT-970, MC-80484: Disallow NBT pick block on chests." And actually paper has a related patch to disable this (see [Allow-chests-to-be-placed-with-NBT-data.patch](https://github.com/PaperMC/Paper/blob/master/patches/server/0256-Allow-chests-to-be-placed-with-NBT-data.patch)). I'm not sure how this is related to plugin system.
