### ISSUE TITLE
[All] Duplicate any GUI using Quark

### ISSUE THREAD

**Issue by XionioXMaster** [IzzelAliz/Arclight#722]
### I have confirmed that ...

- [X] Arclight is up to date
- [X] all dependencies are installed
- [X] all plugins and mods are up to date
- [X] unable to reproduce in Spigot
- [X] unable to reproduce in Forge

### Arclight version

arclight-forge-1.18.2-1.0.7-SNAPSHOT.jar

### OS & Java versions

17 windows server 2020

### Plugins and Mods

```raw
Plugins: PlayersKits or other GUI plugin
Mod: Quark
```

### Description

You can drag and drop any item from the GUI using the Extract button in the GUI
![image](https://user-images.githubusercontent.com/86433158/188960720-c9320776-fb1b-474f-b08d-405fe367da17.png)
![image](https://user-images.githubusercontent.com/86433158/188960757-2123532b-09b1-4582-8477-0b5c9433f083.png)

This works on any version of Arclight

### Step to reproduce

^

### Logs

There are absolutely no errors in the console.

**Comment by SirTZN** [comment]
Obviously not a permanent fix, but you can remove inventory sorting / quick moving within the quark config until a better method gets figured out

**Comment by luoxiawuchen** [comment]
To be honest, this should not be a problem on the server side, because the bukkit plug-in can't directly listen to some special mod events without special processing by the author.

I think the best emergency solution is to temporarily close the relevant functions (only keep the sorting, otherwise similar problems may occur with other plug-ins)

For example: quark's wooden card text modification function, the residence plug-in may not be able to monitor and prevent, resulting in the wooden card text in the player's residence being modified by others at will.

**Comment by Dokman** [comment]
i have quark as mod and other plugins and they don't mix
