### ISSUE TITLE
/tp @e <username>

### ISSUE THREAD

**Issue by JAVAHTML1** [IzzelAliz/Arclight#946]
Hello, is there a way to use Forge commands (/tp @e <username> mainly)? I really need it and can not find a plugin that will allow @e on Spigot.

**Comment by Supermarcel10** [comment]
This is part of normal minecraft for newer versions of minecraft. You should be able to run `/tp @e <username>` on the server without the need of any plugins or mods.

If it's not automatically suggesting @e, you can try specifying `/minecraft:tp @e <username>`, incase if any mods are overriding the tp command method.

I'm not quite sure why you'd need this functionality, since this will teleport all loaded-in entities, including any boats, minecarts and modded entities to that player.
